#!/bin/zsh

echo "\033[32;1m   == ===  Deploying the game  === ==   \033[0m"
#cargo run #--target wasm32-unknown-unknown  ##play

#cargo build --target wasm32-unknown-unknown #--release 
#wasm-bindgen --out-dir ./gh-pages/target --target web ./target/wasm32-unknown-unknown/release/game.wasm
wasm-pack build --target web --out-dir ./gh-pages/target --release

#TODO commit main  / do this after commit

git subtree push --prefix gh-pages origin gh-pages


