# TODO disabled - migrate to actions detailed at 
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
# and then debug caching

name: builder
on:
  push:
    branches: [ main ]
env: 
  target: wasm32-unknown-unknown

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}:builder-${{ env.target }}
          build-args: TARGET=${{ env.target }}

# jobs:
#   build-push-game-container:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - run: |
#         export BUILDER="${{env.imgbase}}:${{env.target}}"
#         echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
#         docker pull $BUILDER || :
#         DOCKER_BUILDKIT=1 docker build . -t $BUILDER --build-arg TARGET=${{env.target}} -f ./Dockerfile --cache-from $BUILDER --rm=false
#         docker push $BUILDER
#
