name: ci
on:
  push:
    branches: [ try-merge ]
env: 
  target:                                           wasm32-unknown-unknown
  imgbase: ghcr.io/${{ github.repository }}-builder
  image:   ghcr.io/${{ github.repository }}-builder:wasm32-unknown-unknown              
    #${{ env.imgbase }}:${{ env.target }} does not work because of env

jobs:
  builder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }} 

      - uses: docker/build-push-action@v4
        with:  # automatically checks out git ref
          tags: ${{ env.image }}
          build-args: TARGET=${{ env.target }}
          cache-from: type=registry,ref=${{ env.image }}--cache
          cache-to:   type=registry,ref=${{ env.image }}--cache,mode=max
          push: true


  gh-pages:
    needs: builder
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/beijn/game-builder:wasm32-unknown-unknown
      credentials:
         username: ${{ github.actor }}
         password: ${{ github.token }}
    steps: 
    - uses: actions/checkout@v3
    - run: mv /build/target .  # IMPORTANT get the build cache (cause https://github.com/actions/checkout/pull/388)
    - name: Build for gh-pages
      run: |
        wasm-pack build --target web --out-dir gh-pages --release --no-typescript
        cd gh-pages && rm .gitignore README.md package.json  #took days to find this
    - uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./gh-pages
        github_token: ${{ github.token }}
        force_orphan: true




      # TODO: this yields an error 
      # # push to registry also accumulates older images and thus enforces to use snok/container-retention-policy
      # # TODO: instead of registry one may use --cache-from and -to action/cache
      # - name: Clear old images
      #   uses: snok/container-retention-policy@v2
      #   with:
      #     image-names: ${{ env.imgbase }}
      #     cut-off: A minute ago UTC
      #     account-type: personal
      #     keep-at-least: 1
      #     untagged-only: true
      #     token: ${{ github.token }}


